package dev.connectx.vpn.api

object TunnelContract {
    const val ACTION_START = "dev.connectx.action.START_LOCAL_TUNNEL"
    const val ACTION_STOP = "dev.connectx.action.STOP_LOCAL_TUNNEL"
    const val ACTION_STATUS = "dev.connectx.action.LOCAL_TUNNEL_STATUS"

    const val EXTRA_STATUS = "dev.connectx.extra.TUNNEL_STATUS"
    const val EXTRA_ERROR = "dev.connectx.extra.TUNNEL_ERROR"
    const val EXTRA_ENGINE_MODE = "dev.connectx.extra.ENGINE_MODE"
    const val EXTRA_NATIVE_VERSION = "dev.connectx.extra.NATIVE_VERSION"
    const val EXTRA_NATIVE_ABI = "dev.connectx.extra.NATIVE_ABI"
    const val EXTRA_PROBE_LATENCY_MILLIS = "dev.connectx.extra.PROBE_LATENCY_MILLIS"
    const val EXTRA_PROBE_UPLOADED_BYTES = "dev.connectx.extra.PROBE_UPLOADED_BYTES"
    const val EXTRA_PROBE_DOWNLOADED_BYTES = "dev.connectx.extra.PROBE_DOWNLOADED_BYTES"
    const val EXTRA_PROBE_RELAY_CONNECTIONS = "dev.connectx.extra.PROBE_RELAY_CONNECTIONS"
    const val EXTRA_PROBE_RELAY_ASSOCIATIONS = "dev.connectx.extra.PROBE_RELAY_ASSOCIATIONS"
    const val EXTRA_PROBE_DATAGRAMS = "dev.connectx.extra.PROBE_DATAGRAMS"
    const val EXTRA_PROBE_DNS_QUERIES = "dev.connectx.extra.PROBE_DNS_QUERIES"
    const val EXTRA_PROBE_DNS_RESPONSES = "dev.connectx.extra.PROBE_DNS_RESPONSES"
    const val EXTRA_PROBE_DNS_ANSWER = "dev.connectx.extra.PROBE_DNS_ANSWER"
    const val EXTRA_STRATEGY_ID = "dev.connectx.extra.STRATEGY_ID"
    const val EXTRA_STRATEGY_SEGMENTS = "dev.connectx.extra.STRATEGY_SEGMENTS"
    const val EXTRA_STRATEGY_SPLIT_OFFSET = "dev.connectx.extra.STRATEGY_SPLIT_OFFSET"

    const val MODE_FOUNDATION = "foundation"
    const val MODE_NATIVE_SELF_TEST = "native_self_test"
    const val MODE_NATIVE_TCP_PROBE = "native_tcp_probe"
    const val MODE_NATIVE_UDP_PROBE = "native_udp_probe"
    const val MODE_NATIVE_DNS_PROBE = "native_dns_probe"
    const val MODE_NATIVE_TLS_SPLIT_PROBE = "native_tls_split_probe"

    const val STATUS_STARTED = "started"
    const val STATUS_STOPPED = "stopped"
    const val STATUS_PROBE_SUCCEEDED = "probe_succeeded"
    const val STATUS_UDP_PROBE_SUCCEEDED = "udp_probe_succeeded"
    const val STATUS_DNS_PROBE_SUCCEEDED = "dns_probe_succeeded"
    const val STATUS_STRATEGY_PROBE_SUCCEEDED = "strategy_probe_succeeded"
    const val STATUS_ERROR = "error"
}
